package kim.biryeong.semiontd.augment;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public enum AugmentIconCategory {
    DAMAGE("공격",
            "overheat_core",
            "job_villager_towers_g2",
            "job_undead_towers_g1",
            "job_animal_towers_g2",
            "job_warlock_towers_s",
            "job_warlock_towers_g1",
            "job_legion_towers_g2",
            "job_resonance_towers_g2",
            "job_illager_towers_s",
            "job_illager_towers_g2",
            "job_illager_towers_p",
            "job_nether_s",
            "job_end_towers_s",
            "job_end_towers_g2",
            "job_end_towers_p",
            "job_ocean_g2",
            "job_ancient_city_s",
            "job_ancient_city_g2",
            "job_ancient_city_p",
            "job_hero_party_s",
            "job_hero_party_g2",
            "job_succubus_p",
            "job_adversary_towers_s",
            "job_engineer_towers_s",
            "job_engineer_towers_g1",
            "job_engineer_towers_g2",
            "job_queen_towers_p",
            "job_atlantis_towers_g1",
            "job_atlantis_towers_g2",
            "job_atlantis_towers_p",
            "job_plant_towers_g2",
            "job_army_g1",
            "job_thunder_s",
            "job_thunder_g2",
            "job_thunder_p",
            "job_demon_lord_towers_s",
            "job_demon_lord_towers_p",
            "job_pet_towers_g1",
            "job_developer_towers_g1",
            "job_frost_g2",
            "job_pirate_g2",
            "job_pirate_p",
            "job_mage_towers_g2",
            "engagement_plan_quick",
            "forecast_offensive",
            "winning_barrage",
            "domino_fire",
            "tactical_designation_1_assault",
            "finishing_fire_1",
            "tactical_designation_2_assault",
            "finishing_fire_2",
            "tactical_designation_3_assault",
            "finishing_fire_3"),
    GUARD("보호",
            "job_insect_towers_s",
            "biased_armor_physical",
            "biased_armor_magic",
            "tactical_designation_1_cover",
            "tactical_designation_2_cover",
            "tactical_designation_3_cover"),
    VITALITY("체력",
            "job_villager_towers_p",
            "job_undead_towers_s",
            "job_nether_g1",
            "job_demon_lord_towers_g1",
            "job_body_g2",
            "job_insect_towers_s2",
            "job_insect_towers_g3",
            "additional_payload"),
    REVIVAL("재기",
            "job_undead_towers_g2",
            "job_legion_towers_s",
            "job_nether_g2",
            "job_nether_p",
            "job_insect_towers_g1",
            "job_insect_towers_p",
            "job_future_agency_towers_p"),
    TEMPO("속도",
            "job_resonance_towers_p",
            "job_illager_towers_g1",
            "job_succubus_s",
            "job_engineer_towers_p",
            "job_queen_towers_g1",
            "job_demon_lord_towers_g2",
            "job_body_g1",
            "job_body_p"),
    REACH("조준",
            "job_villager_adv_towers_p",
            "job_ancient_city_g1",
            "job_body_s",
            "job_pet_towers_s",
            "job_mage_towers_p",
            "job_future_agency_towers_g1"),
    CONTROL("제어",
            "job_succubus_g2",
            "job_queen_towers_s",
            "job_atlantis_towers_s",
            "job_plant_towers_s",
            "job_frost_s",
            "job_frost_g1",
            "job_frost_p",
            "job_future_agency_towers_s"),
    GROWTH("성장",
            "job_villager_towers_s",
            "job_villager_towers_g1",
            "job_villager_adv_towers_s",
            "job_villager_adv_towers_g1",
            "job_end_towers_g1",
            "job_adversary_towers_g1",
            "job_adversary_towers_g2",
            "job_plant_towers_g1",
            "job_army_s",
            "job_magic_school_g2",
            "battlefield_mastery"),
    RESOURCE("자원",
            "job_ocean_s",
            "job_ocean_g1",
            "job_ocean_p",
            "job_thunder_g1",
            "job_pirate_s",
            "job_pirate_g1",
            "job_mage_towers_s",
            "job_mage_towers_g1",
            "emergency_loan",
            "support_performance",
            "cash_settlement",
            "forbidden_blueprint",
            "low_pressure_high_yield",
            "reserve_diamonds_silver",
            "reserve_income_silver",
            "reserve_production_silver",
            "reserve_diamonds_gold",
            "reserve_income_gold",
            "reserve_production_gold",
            "reserve_diamonds_prismatic",
            "reserve_income_prismatic",
            "reserve_production_prismatic"),
    DEPLOY("소환",
            "job_undead_towers_p",
            "job_legion_towers_p",
            "job_queen_towers_g2",
            "job_army_g2",
            "job_army_p",
            "job_insect_towers_g2",
            "job_future_agency_towers_g2",
            "folding_barricade_blueprint",
            "pulse_relay_blueprint",
            "barrier_core_call",
            "giant_hunter_call",
            "emergency_bell_blueprint",
            "capacitor_post_blueprint",
            "ambush_workshop_blueprint",
            "starlight_cocoon_call",
            "ordnance_factory_call"),
    SYNERGY("연계",
            "job_villager_adv_towers_g2",
            "job_animal_towers_s",
            "job_animal_towers_p",
            "job_warlock_towers_p",
            "job_resonance_towers_s",
            "job_resonance_towers_g1",
            "job_plant_towers_p",
            "job_pet_towers_p",
            "job_developer_towers_s",
            "job_developer_towers_p",
            "job_magic_school_g1",
            "triangle_formation",
            "twin_squadron",
            "frontline_specialization",
            "independent_position"),
    ENHANCEMENT("강화",
            "job_animal_towers_g1",
            "job_warlock_towers_g2",
            "job_legion_towers_g1",
            "job_hero_party_g1",
            "job_hero_party_p",
            "job_succubus_g1",
            "job_adversary_towers_p",
            "job_pet_towers_g2",
            "job_developer_towers_g2",
            "job_magic_school_s",
            "job_magic_school_p",
            "engagement_plan_long",
            "one_man_show",
            "wartime_economy",
            "beneficial_effect_1",
            "beneficial_effect_2",
            "beneficial_effect_3"),
    FORTUNE("확률",
            "job_gamble_s",
            "job_gamble_g1",
            "job_gamble_g2",
            "job_gamble_p");

    private static final Map<String, AugmentIconCategory> CLASSIFICATIONS = classifications();
    private final String label;
    private final List<String> cardIds;

    AugmentIconCategory(String label, String... cardIds) {
        this.label = label;
        this.cardIds = List.of(cardIds);
    }

    public String label() {
        return label;
    }

    public static Set<String> classifiedIds() {
        return CLASSIFICATIONS.keySet();
    }

    public static AugmentIconCategory of(AugmentDefinition card) {
        var result = CLASSIFICATIONS.get(card.id());
        if (result == null) throw new IllegalArgumentException("Unclassified augment icon: " + card.id());
        return result;
    }

    private static Map<String, AugmentIconCategory> classifications() {
        var result = new HashMap<String, AugmentIconCategory>();
        for (var category : values()) {
            for (String id : category.cardIds) {
                if (result.put(AugmentCatalog.normalizeId(id), category) != null) {
                    throw new IllegalStateException("Duplicate augment icon classification: " + id);
                }
            }
        }
        return Map.copyOf(result);
    }
}
