plugins { id 'net.fabricmc.fabric-loom' }
group = 'me.drex.fafpatch'
version = '4.0.26-0+26.3-local'
base { archivesName = 'friends-and-foes-patch' }
repositories {
    mavenCentral()
    maven { url 'https://maven.nucleoid.xyz' }
    maven { url 'https://maven.isxander.dev/releases' }
    maven { url 'https://api.modrinth.com/maven' }
}
dependencies {
    minecraft 'com.mojang:minecraft:26.3'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.161.0+26.3'
    implementation project(':compat-friends-and-foes')
    implementation 'eu.pb4:factorytools:0.12.1+26.3'
    implementation 'eu.pb4:polymer-core:0.18.2+26.3'
    implementation 'eu.pb4:polymer-blocks:0.18.2+26.3'
    implementation 'eu.pb4:polymer-resource-pack:0.18.2+26.3'
    implementation 'eu.pb4:polymer-resource-pack-extras:0.18.2+26.3'
    implementation 'eu.pb4:polymer-sound-patcher:0.18.2+26.3'
    implementation 'eu.pb4:polymer-autohost:0.18.2+26.3'
    implementation 'eu.pb4:polymer-virtual-entity:0.18.2+26.3'
    implementation 'maven.modrinth:resourceful-lib:P6Jq77km'
    implementation 'maven.modrinth:yacl:3.9.7+26.3-fabric'
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 25 }
java { withSourcesJar() }
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}
jar { from('LICENSE') }